### ISSUE TITLE
My 'open in browser' , does not work.

### ISSUE THREAD

**Issue by RajaZhao** [titoBouzout/SideBarEnhancements#275]
ST 3 3083, right click on the html files and click 'open in browser', it just does nothing...

Ctrl + ` and run the console, paste  'sublime.log_commands(True)', get wrong message:

=================================================
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "SideBar in E:\Sublime Text Build 3083 x64\Data\Installed Packages\SideBarEnhancements.sublime-package", line 1602, in run
  File "SideBarAPI in E:\Sublime Text Build 3083 x64\Data\Installed Packages\SideBarEnhancements.sublime-package", line 314, in url
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 13: illegal multibyte sequence
=================================================

**Comment by chongyuan** [comment]
mac, open in browser
can't work

**Comment by titoBouzout** [comment]
this is unrelated to the package.
