### ISSUE TITLE
"Open in browser" error sre_constants.error: multiple repeat

### ISSUE THREAD

**Issue by nanos** [titoBouzout/SideBarEnhancements#412]
When I attempt to open a file in browser I get the following error in the console:

```
Exception in thread Thread-59:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\{name}\AppData\Roaming\Sublime Text 3\Installed Packages\SideBarEnhancements.sublime-package\SideBar.py", line 2370, in run
    url = item.url(type) or item.uri()
  File "C:\Users\{name}\AppData\Roaming\Sublime Text 3\Installed Packages\SideBarEnhancements.sublime-package\SideBarAPI.py", line 381, in url
    re.compile("^.?*" + re.escape(base), re.IGNORECASE), "", current
  File "./python3.3/re.py", line 214, in compile
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 570, in _parse
sre_constants.error: multiple repeat
```

This is on Windows 10.

**Comment by macboat** [comment]
Same on ubuntu 18.04/ St3

Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/macboat/.config/sublime-text-3/Packages/sidebarenhancements/SideBar.py", line 2370, in run
    url = item.url(type) or item.uri()
  File "/home/macboat/.config/sublime-text-3/Packages/sidebarenhancements/SideBarAPI.py", line 381, in url
    re.compile("^.?*" + re.escape(base), re.IGNORECASE), "", current
  File "./python3.3/re.py", line 214, in compile
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 570, in _parse
sre_constants.error: multiple repeat

**Comment by macboat** [comment]
I was screwing around trying to fix this, all of a sudden it works, I have no clue what caused it.  So I post here: 

1. I installed sbe through package control, not working
2. uninstalled, use the method in read me ( clone to packages/ folder), not working
3. I found you have to set the preview url, and make sure it is the right format, don't forget the outer bracket { }
4. but still not working, and without delete current version, I installed sbe through package control, again, boom, everything works now.
5. but now I have two sbe insalled, all the menus are duplicated.   I deleted the one under packages/ folder.  Everything works in normal now.


I highly recommend you check your preview url setting file make sure the format is correct and then install through package control.

**Comment by nanos** [comment]
Unfortunately that didn't work for me. And I did triple check the format of the preview urls.

**Comment by nanos** [comment]
So, I had completely forgotten about this due to a lack of time, but just had a closer look at this:

This problem was introduced in fixing #405. 

The problem is this regular expression:

    re.compile("^.?*" + re.escape(base), re.IGNORECASE)
 
`^.?*` isn't a valid reg ex. I guess the `?` needs to be removed to fix the immediate issue, but I'm sure this will cause other issues, as it's then very generic indeed?

@titoBouzout  @pilgerone any thoughts?

**Comment by srbs** [comment]
It is possible that the original intention was a non-greedy prefix match of `^.*?` to replace up to the first instance of `base` instead of the last.

**Comment by titoBouzout** [comment]
Yes I have to agree, Ill just revert to the original code till a better implementation gets submitted.
