### ISSUE TITLE
Open In Browser Not working, Ubuntu 18.04, ST3; "sre_constants.error: multiple repeat"

### ISSUE THREAD

**Issue by macboat** [titoBouzout/SideBarEnhancements#413]
Ubuntu 18.04, st 3, please see error message below

Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/macboat/.config/sublime-text-3/Packages/sidebarenhancements/SideBar.py", line 2370, in run
    url = item.url(type) or item.uri()
  File "/home/macboat/.config/sublime-text-3/Packages/sidebarenhancements/SideBarAPI.py", line 381, in url
    re.compile("^.?*" + re.escape(base), re.IGNORECASE), "", current
  File "./python3.3/re.py", line 214, in compile
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 570, in _parse
sre_constants.error: multiple repeat

**Comment by macboat** [comment]
I found another thread 22 days ago with the same issue so close this.
